import "./app.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "The Logbook (Diary) App",
	description: "Generated by create next app - Developed by Paulo Wells",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{children}
			</body>
		</html>
	);
}
